META_REACTOR_SHUTDOWN_EV = 0
from select import (
    POLLIN
    , POLLPRI
    , POLLOUT
    , POLLERR
    , POLLHUP
    , POLLNVAL
    )
META_READ_EV = (POLLIN | POLLPRI)
META_WRITE_EV = POLLOUT
META_DISCONNECTED_EV = (POLLHUP | POLLERR | POLLNVAL)

META_READABLE = (META_READ_EV | META_DISCONNECTED_EV)
